### ISSUE TITLE
Add serializers back into ByteString

### ISSUE THREAD

**Issue by tysonzero** [indicatrix/wkt-geom#7]
It would be ideal if I could freely convert between geojson and ewkb in both directions. Specifically I need my Haskell backend to add new data to PostGIS, not just parse and use existing data.

**Comment by newmana** [comment]
Hi, we've made some progress on this.  But on the way we discovered that wkt, wkb and geojson all have slightly different features that make hard.  As long as you stay within 2d and 3d points that are all the same type.

**Comment by newmana** [comment]
See issue #8
